"""DIMER pipeline for the MediaPipe Face Landmarker task bundle (478 3D landmarks, 52 blendshapes, transformation matrix).

Importing the package imports NumPy and Pillow only; ``mediapipe`` is imported when a landmarker is built, so the bundle
and input checks run (and refuse) without it.
"""

from __future__ import annotations

from .metrics import (
    FAILURE_NME,
    PERTURBATION_KINDS,
    apply_affine,
    bootstrap_ci,
    inter_ocular_distance,
    invert_affine,
    mean_shape_box,
    mean_shape_image,
    nme_iod,
    paired_sanity,
    perturb,
    point_errors,
    rank_auc,
    summarize_nme,
)
from .pipeline import (
    ARCHITECTURE_SOURCE,
    BLENDSHAPE_FIELDS,
    BLENDSHAPE_NAMES,
    BUNDLE_NAME,
    DEFAULT_CONFIDENCE,
    EXPECTED_MEMBERS,
    INPUT_SCHEMA,
    LANDMARK_FIELDS,
    MANIFEST_NAME,
    MAX_FILE_BYTES,
    MAX_IMAGE_PIXELS,
    MAX_IMAGE_SIDE,
    MAX_NUM_FACES,
    MIN_IMAGE_SIDE,
    MODEL_BYTES,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    MODEL_SHA256,
    MODEL_SOURCE_URL,
    MODEL_VERSION,
    NUM_BLENDSHAPES,
    NUM_LANDMARKS,
    SCORE_SEMANTICS,
    FaceLandmarkerPipeline,
    blendshape_rows,
    bundle_url,
    contact_sheet,
    detect_face_boxes,
    draw_overlay,
    face_summary,
    inspect_bundle,
    landmark_rows,
    matrix_records,
    pixel_coordinates,
    read_manifest,
    stage_bundle,
    validate_confidence,
    validate_image,
    validate_num_faces,
    verify_bundle,
    write_csv,
    write_json,
)
from .samples import (
    EYE_CORNERS,
    LANDMARK_MAP,
    LANDMARK_NAMES,
    MEDIAPIPE_INDICES,
    TEMPLATE_INDICES,
    age_band,
    fetch_samples,
    load_manifest,
    manifest_digest,
    parse_template,
    read_info,
    read_template,
    sample_records,
    template_subset,
)

__all__ = [
    "ARCHITECTURE_SOURCE", "BLENDSHAPE_FIELDS", "BLENDSHAPE_NAMES", "BUNDLE_NAME", "DEFAULT_CONFIDENCE", "EXPECTED_MEMBERS",
    "EYE_CORNERS", "FAILURE_NME", "INPUT_SCHEMA", "LANDMARK_FIELDS", "LANDMARK_MAP", "LANDMARK_NAMES", "MANIFEST_NAME",
    "MAX_FILE_BYTES", "MAX_IMAGE_PIXELS", "MAX_IMAGE_SIDE", "MAX_NUM_FACES", "MEDIAPIPE_INDICES", "MIN_IMAGE_SIDE",
    "MODEL_BYTES", "MODEL_ID", "MODEL_KEY", "MODEL_LICENSE", "MODEL_REVISION", "MODEL_SHA256", "MODEL_SOURCE_URL",
    "MODEL_VERSION", "NUM_BLENDSHAPES", "NUM_LANDMARKS", "PERTURBATION_KINDS", "SCORE_SEMANTICS", "TEMPLATE_INDICES",
    "FaceLandmarkerPipeline", "age_band", "apply_affine", "blendshape_rows", "bootstrap_ci", "bundle_url", "contact_sheet",
    "detect_face_boxes", "draw_overlay", "face_summary", "fetch_samples", "inspect_bundle", "inter_ocular_distance",
    "invert_affine", "landmark_rows", "load_manifest", "manifest_digest", "matrix_records", "mean_shape_box",
    "mean_shape_image", "nme_iod", "paired_sanity", "parse_template", "perturb", "pixel_coordinates", "point_errors",
    "rank_auc", "read_info", "read_manifest", "read_template", "sample_records", "stage_bundle", "summarize_nme",
    "template_subset", "validate_confidence", "validate_image", "validate_num_faces", "verify_bundle", "write_csv",
    "write_json",
]  # fmt: skip
